### ISSUE TITLE
Problem przy kompilacji

### ISSUE THREAD

**Issue by pidzej** [v3l0c1r4pt0r/delz#14]
Podczas kompilacji dostaję takie ostrzeżenia 

- gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)  64BIT

@dev ~/delz/src $ make
cc  -c delz.c
cc  -c lz.c
lz.c: In function ‘get_error’:
lz.c:130:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "overflowed src buffer at exit", error);
                          ^
lz.c:133:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "num of bytes to copy exceeds dst size", error);
                          ^
lz.c:136:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "copy offset before start of buffer", error);
                          ^
lz.c:139:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "overflowed src while reading length", error);
                          ^
lz.c:142:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "length greater than dst buffer", error);
                          ^
lz.c:145:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "overflowed src while reading raw byte", error);
                          ^
lz.c:148:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "overflowed dst while writing raw byte", error);
                          ^
lz.c:151:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "overflowed src after reading offset", error);
                          ^
lz.c:154:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "overflowed src while reading offset", error);
                          ^
lz.c:157:26: warning: too many arguments for format [-Wformat-extra-args]
             sprintf(ret, "offset exceeds maximum", error);
                          ^
ar cr liblz.a lz.o
cc  -o delz delz.o liblz.a

**Comment by v3l0c1r4pt0r** [comment]
Fixed.
