### ISSUE TITLE
iconv error: invalid argument

### ISSUE THREAD

**Issue by mokry** [v3l0c1r4pt0r/delz#3]
Hi,
When I'm trying to command "./delz < data.lzs > data.txt" I have an error:
iconv: invalid argument

**Comment by v3l0c1r4pt0r** [comment]
Could you post what bytes do you have at about 'in - 10' pointer? If I am right it should contain last 5 characters of data, so there should not be any sensitive data. Or maybe you could examine data before conversion manually?

**Comment by mokry** [comment]
I think I can send you by @ all my base64 encoded string (I don't see here private messaging system).

**Comment by v3l0c1r4pt0r** [comment]
If you trust me that much :), then ok. Contact me at v3l0c1r4pt0r at gmail dot com.

**Comment by mokry** [comment]
Sorry for my mistake. My code was badly read by scanner.

Btw. Do you know any library for Android to scan Aztec codes which I could use in my Android app? Unfortunately, zxing have some problems with reading Aztec code in polish vehicle registration certificate.

**Comment by v3l0c1r4pt0r** [comment]
Then I am closing the issue.

No, I don't know any library for Aztec scanning.
