### ISSUE TITLE
Java implementation

### ISSUE THREAD

**Issue by cybuch** [v3l0c1r4pt0r/delz#7]
Hi,
is it possible to provide Java imlementation?

**Comment by qoobaa** [comment]
Probably JavaScript would be nicer and more useful.

**Comment by cybuch** [comment]
Doesn't matter, JS can be easily executed from JVM so it's fine for me ;)

**Comment by v3l0c1r4pt0r** [comment]
Sorry, but I am not planning to provide any other implementation. Although there is AFAIK at least one Java implementation. I do not remember, where I saw it, but it for sure could still be found. It have also unknown license so using it anywhere may not be a good idea, but can be used as assistance to write another one.

You could also rewrite this code yourself. I think most of the code is clear enough to use it as documentation. If you will have any question about how the algorithm works, you are free to contact me by e-mail (I gave the address in another issue).
